[project]
name = 'decentralized-insurance-pool'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.insurance-pool]
path = 'contracts/insurance-pool.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
